version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: {POSTGRES_PASSWORD}
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
      - GOOGLE_APPLICATION_CREDENTIALS={path-to-credential-path-inside the container}
    volumes:
      - C:\Users\ramma\AppData\Roaming\gcloud\application_default_credentials.json:/tmp/keys/application_default_credentials.json:ro
    depends_on:
      - db